### ISSUE TITLE
Horse jump wrong in MC 1.9+

### ISSUE THREAD

**Issue by Xericore** [cyilin/zyinhud#11]
Hi, as of MC 1.9+, mojang nerfed the horse jump strength.
For a horse with an internal value of jump strength of 1.0, ZynsHud shows a block jump height of 5.92. But the actual jump strength in 1.9+ is ~5.29.

The new formula for jump strength in blocks is ([source](http://minecraft.gamepedia.com/Horse#Statistics)):
`double jumpHeightInBlocks = (-0.1817584952 * Math.pow(x, 3)) + (3.689713992 * Math.pow(x, 2)) + (2.128599134 * x) - 0.343930367;`
where x is the internal jump strength ranging from 0.4 to 1.0. (should be `double x = horse.getHorseJumpStrength()`);

I wanted to give you a pull request, but the ZynsHud version I build from source code caused the game to crash on startup, thus I created this ticket. All I changed was `AnimalInfo.GetHorseMaxJump();`, but that didn't work.

**Comment by cyilin** [comment]
Thanks
