### ISSUE TITLE
crash on use of save button

### ISSUE THREAD

**Issue by Maccool** [cyilin/zyinhud#3]
I tried a modification of some  of the options in the mod, got crash on the save. Linux, MC 1.10.2, connected to a local server game. The crash report looked like:

http://pastebin.com/7UQcrvZ2

The latest.log was:

http://pastebin.com/bVDxP5ji

Crashes as well with the ESC key after no modifications made. Also, got a crash when trying to select items on the 2nd menu page (like trying to display the ender pearl aid, or eating aid, maybe others). 

I'm  off to try updates by changing the config file with a text editor. Thanks

**Comment by cyilin** [comment]
Fixed, try latest version https://github.com/cyilin/zyinhud/releases

**Comment by Maccool** [comment]
Most excellent!
