### ISSUE TITLE
Placed String (Tripwire) Appears to Vanish on Reconnect (Multiplayer)

### ISSUE THREAD

**Issue by LakenH** [cyilin/zyinhud#5]
## Overview
Placed string (tripwire), will "disappear" when reconnecting to a server. The hitbox also "disappears", however, it is still there, as it can still be triggered by walking over it or dropping an item on it
## Reproduction
Place string on the ground, then leave and join again. Observe that the string is now invisible. I have tested this on a vanilla server, and one running Paper Spigot. This is using mod version 1.5.3.10.
## Video
[video of this bug on a vanilla server](https://streamable.com/d4rgb)

**Comment by LakenH** [comment]
Appears that this is actually caused by my outdated version of Forge
Edit: Actually, updating forge didn't fix this, this is a forge issue. It even happens when I have no mods loaded in forge. So this isn't a Zyin's issue at all.

**Comment by cyilin** [comment]
you can report this bug to Forge https://github.com/MinecraftForge/MinecraftForge/issues
