### ISSUE TITLE
Minecraft Crashes when trying to adjust the FOV in Options

### ISSUE THREAD

**Issue by RepoDraghon** [cyilin/zyinhud#9]
I have asked around with the logs in hand (so to speak) and no one seems to want to help...
the latest for 1.10.2 crashes when in the world and on the main screen's options menu the FOV bar if clicked on will crash the game... I have responded about this on the Minecraft Forums, currently 2nd to last comment with the link to another post to the crash log.

**Comment by RepoDraghon** [comment]
I'm sorry, I don't understand this site, by you closing this does it mean you fixed the issue already, working on it, read the comment or what? if you fixed it already, where is the new version? cause the 1.11 versions wont work on 1.10.2

**Comment by cyilin** [comment]
This bug fixed in latest version (for MC 1.11.2), 1.10.2 version are no longer updated.
